# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
 use_frameworks!

target 'ZhiBo' do

    pod 'Alamofire'
  # Pods for ZhiBo

  target 'ZhiBoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZhiBoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
